############### Routes for displaying pages ###############

home:
  path: '/'
  controller: 'App\Controller\HomeController::index'

darts:
  path: '/darts'
  controller: 'App\Controller\DartsController::index'

new-game:
  path: '/new-game'
  controller: 'App\Controller\NewGameController::index'

game:
  path: '/game/{id}'
  controller: 'App\Controller\GameController::index'
#  methods: [ 'GET' ]
#  requirements:
#    id: '\d+' # Ensure that the id parameter is a digit

player:
  path: '/player'
  controller: 'App\Controller\PlayerController::index'

user:
  path: '/user'
  controller: 'App\Controller\UserController::index'

settings:
  path: '/settings'
  controller: 'App\Controller\SettingsController::index'

profile:
  path: '/profile'
  controller: 'App\Controller\ProfileController::index'

login:
  path: '/login'
  controller: 'App\Controller\LoginController::index'

logout:
  path: '/logout'

# TODO: Remove
match:
  path: '/match'
  controller: 'App\Controller\MatchController::index'





######################## API Routes #######################

api_login_check:
  path: /api/login_check

############ Player

api_get_players:
  path: '/api/player'
  controller: 'App\Controller\PlayerController::getPlayers'
  methods: ['GET']

api_get_player_by_id:
  path: '/api/player/id/{id}'
  controller: 'App\Controller\PlayerController::getPlayerById'
  methods: ['GET']

api_get_players_no_user:
  path: '/api/player/no-user'
  controller: 'App\Controller\PlayerController::getPlayersWithoutUser'
  methods: ['GET']

api_post_player:
  path: '/api/player'
  controller: 'App\Controller\PlayerController::postPlayer'
  methods: ['POST']

api_delete_player:
  path: '/api/player/{id}'
  controller: 'App\Controller\PlayerController::deletePlayer'
  methods: ['DELETE']

############ User

api_get_users:
  path: '/api/user'
  controller: 'App\Controller\UserController::getUsers'
  methods: ['GET']

api_get_user:
  path: '/api/user/{id}'
  controller: 'App\Controller\UserController::getUserById'
  methods: ['GET']

api_post_user:
  path: '/api/user'
  controller: 'App\Controller\UserController::postUser'
  methods: ['POST']

api_delete_user:
  path: '/api/user/{id}'
  controller: 'App\Controller\UserController::deleteUser'
  methods: ['DELETE']

############ Game

api_get_game:
  path: '/api/game/{id}'
  controller: 'App\Controller\GameController::getGame'
  methods: ['GET']
  requirements:
    id: '\d+' # Ensure that the id parameter is a digit

api_post_game:
  path: '/api/game'
  controller: 'App\Controller\GameController::postGame'
  methods: ['POST']




