name: symfonyproject
recipe: symfony

excludes:
  - "DartScorer/var/cache"
  - "DartScorer/vendor"
  - "DartScorer/node_modules"

services:
  appserver:
    webroot: ./DartScorer/public
    type: 'php:8.2'
    via: 'apache:2.4'
    ssl: true
    build_as_root:
      - apt-get update
      - apt-get install nano
      - apt-get install nodejs npm

  database:
    app_mount: disabled
    type: "mysql:8.0"
    creds:
      user: "symfony"
      password: "symfony"
      database: "symfony"
    overrides:
      image: "bitnami/mysql:8.0.36-debian-12-r12"
      ports:
        - '3306:3307'
    healthcheck:
      command: mysql -uroot --silent --execute "SHOW DATABASES;"
      retry: 5
      delay: 5000

  mercure:
    #app_mount: false
    type: compose
    services:
      image: dunglas/mercure
      command: caddy run -c /etc/caddy/Caddyfile.dev
      environment:
        SERVER_NAME: ':80'
        MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
        MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      ports:
        - 3000:80
      #volumes:
        #- ./.lando/Caddyfile.dev:/etc/caddy/Caddyfile.dev

tooling:
  console:
    service: appserver
    cmd: php bin/console
    dir: /app/DartScorer
    description: Runs console commands

  node:install:
    service: appserver
    cmd: ./install-nodejs.sh
    user: root
    dir: /app/.lando
    description: Installs NodeJS

  npm-watch:
    service: appserver
    cmd: npm run watch
    dir: /app/DartScorer
    description: Starts npm watcher